name: Build executable

on: push

jobs:
  build:
    name: Build executable ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    env:
      PYOXIDIZER_VERSION: "0.19.0"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Linux"
            os: ubuntu-latest
          }
        - {
            name: "macOS"
            os: macos-latest"
          }

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache PyOxidizer
        uses: actions/cache@v2
        with:
          key: v1-PyOxidizer-${{ runner.os }}-${{ env.PYOXIDIZER_VERSION }}

      - name: Install PyOxidizer
        run: cargo install --version=${{ env.PYOXIDIZER_VERSION }} pyoxidizer

      - name: Run PyOxidizer
        run: pyoxidizer build --release

      - uses: actions/upload-artifact@v2
        with:
          name: binary for ${{ matrix.os }}
          path: ./build/**/release/install/*

