name: Build executable

on: push

jobs:
  build:
    name: Build executable for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    env:
      PYOXIDIZER_VERSION: "0.19.0"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Linux",
            os: ubuntu-latest,
            target: pyoxidizer-test,
            strip: true,
          }
        - {
            name: "macOS",
            os: macos-latest,
            target: pyoxidizer-test,
            strip: true,
          }
        - {
            name: "Windows",
            os: windows-latest,
            target: pyoxidizer-test.exe,
            strip: false,
          }

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Restore cache
        uses: actions/cache@v2
        with:
          key: v3-PyOxidizer-${{ runner.os }}-${{ env.PYOXIDIZER_VERSION }}
          path: |
            ~/.cargo
            ~/.cache/pyoxidizer

      - name: Install PyOxidizer
        run: cargo install --version=${{ env.PYOXIDIZER_VERSION }} pyoxidizer

      - name: Run PyOxidizer
        shell: bash
        run: |
          pyoxidizer build --release

      - name: Strip and compress executable
        uses: svenstaro/upx-action@v1
        with:
          version: latest
          args: -9 -q
          file: build/**/release/install/${{ matrix.config.target }}
          strip: ${{ matrix.config.strip }}

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ./build/**/release/install/*

