name: Build executable

on: push

jobs:
  build:
    name: Build executable for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    env:
      PYOXIDIZER_VERSION: "0.19.0"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Linux",
            os: ubuntu-latest,
            pyoxidizer_cache_dir: "${{ env.HOME }}/.cache/pyoxidizer",
          }
        - {
            name: "macOS",
            os: macos-latest,
            pyoxidizer_cache_dir: "${{ env.HOME }}/.cache/pyoxidizer",
          }
        - {
            name: "Windows",
            os: windows-latest,
            pyoxidizer_cache_dir: "${{ env.HOME }}/.cache/pyoxidizer",
          }

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Restore cache
        uses: actions/cache@v2
        with:
          key: v2-PyOxidizer-${{ runner.os }}-${{ env.PYOXIDIZER_VERSION }}
          path: |
            ~/.cargo
            ~/.cache/pyoxidizer

      - name: Install PyOxidizer
        run: cargo install --version=${{ env.PYOXIDIZER_VERSION }} pyoxidizer

      - name: Run PyOxidizer
        shell: bash
        env:
          PYOXIDIZER_CACHE_DIR: ${{ matrix.config.pyoxidizer_cache_dir }}
        run: |
          if [ ! -d ${PYOXIDIZER_CACHE_DIR} ]; then
            mkdir -p ${PYOXIDIZER_CACHE_DIR}
          fi
          pyoxidizer build --release

      - name: Strip executable
        run: strip build/**/release/install/*
        if: matrix.os != 'windows-latest'

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ./build/**/release/install/*

